class A { 
	method m1() { throw new Exception(message="hello you see") }
}

test "Test catch without type" {

	const a = new A()

	try {
		a.m1()
		assert.fail("Should have thrown exception")
	}

	catch e {
		// ok !
		assert.equals("hello you see", e.message())
	}

}