class A { 
	method m1() { throw new Exception("hello you see") }
}

test "Test message not understood" {

	const a = new A()
				
	try {
		a.m2()
		assert.fail("Should have thrown message not understood")
	}	
	
	catch e : MessageNotUnderstoodException {
		// ok !
	}
}