class MyException inherits Exception {}
class A {
	method m1() { throw new MyException() }
}

test "Test throw and catch"{
	
	const a = new A()
	var counter = 1
				
	try {
		a.m1()
		counter = 0
	}
	
	catch e : MyException {
    counter = counter + 1
	}

	assert.equals(2, counter)
	
}