object cuenta {
	method sacar(monto) {
		try {
			if (monto > 0)
			throw new Exception("saldo insuficiente")
			return 19
		} 
		catch e {
			return 20
		}
	}

}

describe "catching errors" {

  test "Test catch with a return statement returning from try body and from catch" {
    assert.equals(20, cuenta.sacar(10))
    assert.equals(19, cuenta.sacar(0))
  }

}