import wollok.lang.Exception

class MyExceptionWithCustomMessage inherits Exception {
	method customMessage() { 
		return "Something went wrong"
	}
}

class B { method m1() { throw new MyExceptionWithCustomMessage() } }

test "Test catch using the exception variable" {
	const b = new B()
	var result = null
	try {
		b.m1()
	} catch e : MyExceptionWithCustomMessage
		result = e.customMessage()
	assert.equals("Something went wrong", result)
}