class A { 
	method m1(a) { return a + 1 }
}

test "Test message not understood however 1" {

	const a = new A()

	try {
		a.m1()
		assert.fail("Should have thrown message not understood")
	}

	catch e : MessageNotUnderstoodException {
		// ok !
	}

}