test "Assert throws exception failing" {
	
	var a = 0
	assert.throwsExceptionLike(
		new AssertionException("Block { a + 1 } should have failed"),
		{ assert.throwsException({ a + 1 }) }
	)

}