
test "Test exception from native method gets wrapped into a WollokException" {

	try {
		2 / 0
    assert.fail()
	}
	catch e : BadParameterException {
  }
			
}