class MyException inherits Exception {}
class A {
	method m1() { throw new MyException() }
}

test "Test throw and catch"{
	
	const a = new A()
	var counter = 0
				
	try {
		a.m1()
		counter = counter + 1
	}
	
	catch e : MyException {
		console.println("Exception raised!") // OK!
		e.printStackTrace()
	}

	assert.equals(0, counter)
	
}