
test "Test exception from native method gets wrapped into a WollokException" {

	try {
		console.println(2 / 0)
	}
	
	catch e : Exception {
		
		e.printStackTrace()
		assert.equals("/ by zero", e.getMessage())
	}
	
	
			
}