class C {
	method foo() {
		self.error("Gently failling!")
	}
}

test "Test error method on wollok object" {

	try {
		const f = new C()
		f.foo()
	}
	
	catch e {
		// OK !
		assert.equals("Gently failling!", e.getMessage())
	}
}